"""
Models for request and response of the invoke lisa endpoint.
"""

from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field


class LisaMessage(BaseModel):
    role: Literal["user", "assistant"] = Field(
        ...,
        description="Role of the entity in the conversation. Can be 'user' or 'assistant'.",
    )
    content: str = Field(..., description="The content of the message.")


class LisaChatReqeuest(BaseModel):
    chatId: str = Field(..., description="Chat Id to be processed")
    messages: List[LisaMessage] = Field(
        ..., description="A list of messages between the user and the assistant."
    )
    userId: int = Field(..., description="The unique identifier for the user.")
    organizationId: int = Field(
        ..., description="The unique identifier for the organization."
    )


class InvokeLisaResponse(BaseModel):
    message: List[LisaMessage] = Field(
        ..., description="The final response message(s) generated by Lisa."
    )
    workflow: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Optional list of workflow details associated with the response. This will be rendered by ai-persona-hub",
    )
